### 
GET http://localhost:3000/notes/

### 
curl -X POST -H "Content-Type: application/json" -d 
'{"noteId": 8, "noteTitle": "New Note", "noteContent": "This is the content of the new note."}'
 http://localhost:3000/notes/

###
GET  http://localhost:3000/notes/6


###
curl -X PUT -H "Content-Type: application/json" -
 '{"noteTitle": "Updated Title", "noteContent": "Updated Content"}'
  http://localhost:3000/notes/1


###
DELETE http://localhost:3000/notes/7